{"name": "ultrabug_py3status_Py3status._get_credentials", "language": "py", "prompt": "def _get_credentials(self):\n        \"\"\"\n        stored valid ##ates credentials from storage.\n\n        If nothing has been stored, or if the stored credentials are invalid,\n        the OAuth2 flow is completed to obtain the . credentials.\n\n        Returns: Credentials, the obtained credential.\n        \"\"\"", "tests": "", "completions": ["\n        credentials = None\n        if os.path.exists(self.config_path):\n            with open(self.config_path) as json_file:\n                credentials = Credentials.from_authorized_user_info(json.load(json_file))\n\n        if not credentials or not credentials.valid:\n            if credentials and credentials.expired and credentials.refresh_token:\n                credentials.refresh(Request())\n            else:\n                flow = InstalledAppFlow.from_client_secrets_file(self.client_secret_path,\n                                                                 self.scopes)\n                credentials = flow.run_console()\n            # Save the credentials for the next run\n            with open(self.config_path, 'w') as json_file:\n                json.dump(credentials.to_json(), json_file)\n\n        return credentials\n"], "stop_tokens": ["\ndef", "\n#", "\nif", "\nclass"], "tokens": [], "softmax": []}